### ISSUE TITLE
2.3.8破解失败

### ISSUE THREAD

**Issue by yhan219** [CrazyBunQnQ/multimarkdown#1]
如题

**Comment by CrazyBunQnQ** [comment]
我看下

**Comment by CrazyBunQnQ** [comment]
我看了下，原来的那两个 class 文件是没问题的，你是不是更新了 IDEA 版本？更新了 IDEA 版本之后插件目录变了，也就是你需要重新来一遍，修改当前版本的插件。
![不同版本的配置目录不同](http://wx3.sinaimg.cn/mw690/a6e9cb00ly1fi35rai9fnj20a501at8h.jpg)

**Comment by yhan219** [comment]
![image](https://user-images.githubusercontent.com/12593660/28855848-fdf7d828-7771-11e7-963a-dfe081c5cc93.png)
按照步骤替换class失败。报错如上。直接用打包好的jar也不行，这个jar好像有问题，用360压缩打不开，替换上去也没破解。

**Comment by CrazyBunQnQ** [comment]
奇怪了。。。我这无法复现你这个问题= =，Windows 和 Mac 环境都可以，要不你先从设置里卸载插件，重新安装一下最新的插件，然后关闭 IDEA 去替换 jar 包再启动呢？

**Comment by CrazyBunQnQ** [comment]
[这有个类似的问题](https://stackoverflow.com/questions/20518702/classformaterror-incompatible-magic-value)，报错也是 `Incompatible magic value 168430090 in class file ...`。

**Comment by yhan219** [comment]
直接用jar包替换就可以用了。thu
